import { apiRequest } from './client';

export type AnalyticsPeriod = 'day' | 'week' | 'month' | 'year' | 'custom';
export type AnalyticsQuery = { period: AnalyticsPeriod; from?: string; to?: string };
export type MoneyTotal = { currency: string; amount: string };
export type MoneyComparison = { currency: string; current: number; previous: number; percentChange: number | null };
export type TrendPoint = MoneyTotal & { bucket: string; count: number };
export type PeriodMetadata = { preset: AnalyticsPeriod; current: { from: string; to: string; bucket: string }; previous: { from: string; to: string; bucket: string } };
type Comparison = { current: number; previous: number; percentChange: number | null };

export type BuyerAnalytics = { period: PeriodMetadata; current: { dashboardSummary: { orders: number; averageOrderValue: MoneyTotal[]; spending: MoneyTotal[] }; spendingTrends: TrendPoint[]; orderHistorySummary: Array<{ status: string; count: number }>; favouriteCategories: Array<{ categoryId: string; categoryName: string; spending: string; quantity: string; orders: number }> }; comparison: { orders: Comparison; spending: MoneyComparison[] } };
export type FarmerAnalytics = { period: PeriodMetadata; snapshot: { lowStockSummary: { count: number; products: Array<{ productId: string; productName: string; available: string; reorderLevel: string }> }; productSummary: { total: number; active: number }; inventoryStock: Array<{ unit: string; quantity: string }> }; current: { revenue: MoneyTotal[]; salesTrends: TrendPoint[]; topProducts: Array<{ productId: string; productName: string; unit: string; currency: string; revenue: string; quantity: string; orders: number }>; inventoryTurnover: Array<{ productId: string; productName: string; unit: string; soldQuantity: string; averageInventory: string; turnover: string }>; orderStatusDistribution: Array<{ status: string; count: number }> }; comparison: { revenue: MoneyComparison[] } };
export type TransporterAnalytics = { period: PeriodMetadata; current: { availableJobs: number; acceptedDeliveries: number; deliveriesCompleted: number; earnings: MoneyTotal[]; acceptanceRate: number; completionRate: number; deliveryStatusDistribution: Array<{ status: string; count: number }>; deliveryTrends: TrendPoint[] }; comparison: { deliveriesCompleted: Comparison; earnings: MoneyComparison[]; acceptanceRate: Comparison; completionRate: Comparison } };
export type AdminAnalytics = { period: PeriodMetadata; current: { platformOverview: { newUsers: number; totalUsers: number; activeFarmers: number; activeTransporters: number; pendingFarmers: number; pendingTransporters: number; orders: number; totalOrders: number; products: number; totalProducts: number; categories: number; totalCategories: number; revenue: MoneyTotal[] }; recentRegistrations: Array<{ id: string; name: string; email: string; role: string; createdAt: string }>; userGrowth: { trend: Array<{ bucket: string; role: string; count: number }>; byRole: Array<{ role: string; count: number }> }; orders: { total: number; cumulativeTotal: number; trend: TrendPoint[]; byStatus: Array<{ status: string; count: number }> }; products: { total: number; cumulativeTotal: number; byStatus: Array<{ status: string; count: number }> }; categories: { total: number; cumulativeTotal: number; performance: Array<{ categoryId: string; categoryName: string; currency: string; revenue: string; orders: number }> }; farmerPerformance: Array<{ farmerId: string; farmName: string; currency: string; revenue: string; orders: number }>; transporterPerformance: Array<{ transporterId: string; businessName: string | null; currency: string; earnings: string; deliveries: number }> }; comparison: { newUsers: Comparison; orders: Comparison; products: Comparison; categories: Comparison; revenue: MoneyComparison[] } };

function queryString(query: AnalyticsQuery) { const params = new URLSearchParams({ period: query.period }); if (query.from) params.set('from', query.from); if (query.to) params.set('to', query.to); return params.toString(); }
export const analyticsQueryKeys = { role: (role: string, query: AnalyticsQuery) => ['analytics', role, query] as const };
export const getBuyerAnalytics = (query: AnalyticsQuery) => apiRequest<BuyerAnalytics>(`/analytics/buyer?${queryString(query)}`, { authenticated: true });
export const getFarmerAnalytics = (query: AnalyticsQuery) => apiRequest<FarmerAnalytics>(`/analytics/farmer?${queryString(query)}`, { authenticated: true });
export const getTransporterAnalytics = (query: AnalyticsQuery) => apiRequest<TransporterAnalytics>(`/analytics/transporter?${queryString(query)}`, { authenticated: true });
export const getAdminAnalytics = (query: AnalyticsQuery) => apiRequest<AdminAnalytics>(`/analytics/admin?${queryString(query)}`, { authenticated: true });
