import { Prisma, type PrismaClient } from '@prisma/client';
import type { UploadedImage } from '../utils/cloudinary-media';
import { BaseRepository } from './base.repository';

const audit = (actorId: string, action: string, entityType: string, entityId: string, requestId: string, after?: Prisma.InputJsonValue) => ({ actorId, action, entityType, entityId, requestId, ...(after ? { after } : {}) });

export class MediaRepository extends BaseRepository {
  public constructor(database: PrismaClient) { super(database); }
  public findProduct(id: string) { return this.database.product.findFirst({ where: { id, deletedAt: null }, include: { farmer: { select: { userId: true } }, images: { orderBy: { sortOrder: 'asc' } } } }); }
  public findImage(id: string) { return this.database.productImage.findUnique({ where: { id } }); }
  public async addProductImages(productId: string, images: UploadedImage[], altText: string | undefined, actorId: string, requestId: string) {
    return this.database.$transaction(async tx => {
      const current = await tx.productImage.count({ where: { productId } });
      const created = [];
      for (const [index, image] of images.entries()) created.push(await tx.productImage.create({ data: { productId, storageKey: image.publicId, url: image.secureUrl, width: image.width, height: image.height, bytes: image.bytes, format: image.format, metadata: image.metadata, ...(altText ? { altText } : {}), sortOrder: current + index, isPrimary: current === 0 && index === 0 } }));
      await tx.auditLog.create({ data: audit(actorId, 'PRODUCT_IMAGES_UPLOADED', 'Product', productId, requestId, { imageIds: created.map(item => item.id) }) });
      return created;
    });
  }
  public async reorderProductImages(productId: string, imageIds: string[], actorId: string, requestId: string) { return this.database.$transaction(async tx => { const existing = await tx.productImage.findMany({ where: { productId }, select: { id: true } }); if (existing.length !== imageIds.length || existing.some(item => !imageIds.includes(item.id))) throw new Error('IMAGE_SET_MISMATCH'); for (const [sortOrder, id] of imageIds.entries()) await tx.productImage.update({ where: { id }, data: { sortOrder: -(sortOrder + 1) } }); for (const [sortOrder, id] of imageIds.entries()) await tx.productImage.update({ where: { id }, data: { sortOrder } }); await tx.auditLog.create({ data: audit(actorId, 'PRODUCT_IMAGES_REORDERED', 'Product', productId, requestId, { imageIds }) }); return tx.productImage.findMany({ where: { productId }, orderBy: { sortOrder: 'asc' } }); }); }
  public async setPrimaryImage(productId: string, imageId: string, actorId: string, requestId: string) { return this.database.$transaction(async tx => { const images = await tx.productImage.findMany({ where: { productId }, orderBy: { sortOrder: 'asc' } }); const ordered = [imageId, ...images.filter(image => image.id !== imageId).map(image => image.id)]; await tx.productImage.updateMany({ where: { productId, isPrimary: true }, data: { isPrimary: false } }); for (const [sortOrder, id] of ordered.entries()) await tx.productImage.update({ where: { id }, data: { sortOrder: -(sortOrder + 1) } }); for (const [sortOrder, id] of ordered.entries()) await tx.productImage.update({ where: { id }, data: { sortOrder, isPrimary: id === imageId } }); await tx.auditLog.create({ data: audit(actorId, 'PRODUCT_PRIMARY_IMAGE_SET', 'ProductImage', imageId, requestId) }); return tx.productImage.findUniqueOrThrow({ where: { id: imageId } }); }); }
  public async deleteProductImage(productId: string, imageId: string, actorId: string, requestId: string) { return this.database.$transaction(async tx => { const image = await tx.productImage.delete({ where: { id: imageId } }); const remaining = await tx.productImage.findMany({ where: { productId }, orderBy: { sortOrder: 'asc' } }); for (const [sortOrder, item] of remaining.entries()) await tx.productImage.update({ where: { id: item.id }, data: { sortOrder, ...(image.isPrimary && sortOrder === 0 ? { isPrimary: true } : {}) } }); await tx.auditLog.create({ data: audit(actorId, 'PRODUCT_IMAGE_DELETED', 'ProductImage', imageId, requestId) }); return image; }); }
  public findProfile(userId: string) { return this.database.profile.findUnique({ where: { userId } }); }
  public async updateAvatar(userId: string, image: UploadedImage, requestId: string) { return this.database.$transaction(async tx => { const profile = await tx.profile.update({ where: { userId }, data: { avatarUrl: image.secureUrl, avatarPublicId: image.publicId, avatarMetadata: { width: image.width, height: image.height, bytes: image.bytes, format: image.format, ...image.metadata } } }); await tx.auditLog.create({ data: audit(userId, 'PROFILE_IMAGE_UPDATED', 'Profile', profile.id, requestId) }); return profile; }); }
  public async deleteAvatar(userId: string, requestId: string) { return this.database.$transaction(async tx => { const profile = await tx.profile.update({ where: { userId }, data: { avatarUrl: null, avatarPublicId: null, avatarMetadata: Prisma.DbNull } }); await tx.auditLog.create({ data: audit(userId, 'PROFILE_IMAGE_DELETED', 'Profile', profile.id, requestId) }); return profile; }); }
  public findDelivery(id: string) { return this.database.delivery.findUnique({ where: { id }, include: { farmerOrder: { include: { farmer: { select: { userId: true } } } }, transportJob: { select: { acceptedById: true } } } }); }
  public async updateProof(deliveryId: string, image: UploadedImage, input: { receiverName: string; receiverSignature?: string; notes?: string }, actorId: string, requestId: string) { return this.database.$transaction(async tx => { const delivery = await tx.delivery.update({ where: { id: deliveryId }, data: { proofStorageKey: image.publicId, proofUrl: image.secureUrl, proofUploadedById: actorId, proofPhotoMetadata: { width: image.width, height: image.height, bytes: image.bytes, format: image.format, ...image.metadata }, recipientName: input.receiverName, ...(input.receiverSignature ? { receiverSignature: input.receiverSignature } : {}), ...(input.notes ? { recipientNote: input.notes } : {}) } }); await tx.auditLog.create({ data: audit(actorId, 'PROOF_OF_DELIVERY_UPLOADED', 'Delivery', deliveryId, requestId, { publicId: image.publicId }) }); return delivery; }); }
}
