import { EmailDeliveryStatus, NotificationChannel, NotificationStatus, Prisma, type PrismaClient } from '@prisma/client';
import type { RenderedNotification } from '../constants/notification-templates';
import type { DomainEvent } from '../types/domain-events';
import type { CreateNotificationInput, NotificationActor, NotificationQuery } from '../types/notification';
import { BaseRepository } from './base.repository';

export class NotificationRepository extends BaseRepository {
  public constructor(database: PrismaClient) { super(database); }
  public findRecipients(userIds: string[]) { return this.database.user.findMany({ where: { id: { in: userIds }, deletedAt: null }, select: { id: true, email: true } }); }
  public createFromEvent(userId: string, event: DomainEvent, rendered: RenderedNotification) { return this.database.notification.upsert({ where: { eventId_userId: { eventId: event.id, userId } }, create: { eventId: event.id, userId, type: rendered.type, channels: rendered.channels, status: NotificationStatus.UNREAD, emailStatus: rendered.channels.includes(NotificationChannel.EMAIL) ? EmailDeliveryStatus.PENDING : null, title: rendered.title, body: rendered.body, ...(rendered.data ? { data: rendered.data } : {}) }, update: {} }); }
  public async createManual(eventId: string, input: CreateNotificationInput, actor: NotificationActor) { return this.database.$transaction(async transaction => { const item = await transaction.notification.create({ data: { eventId, userId: input.recipientId, type: input.type, channels: input.channels, emailStatus: input.channels.includes(NotificationChannel.EMAIL) ? EmailDeliveryStatus.PENDING : null, title: input.title, body: input.body, ...(input.data ? { data: input.data } : {}) }, include: { user: { select: { email: true } } } }); await transaction.auditLog.create({ data: { actorId: actor.userId, action: 'NOTIFICATION_CREATED', entityType: 'Notification', entityId: item.id, requestId: actor.requestId } }); return item; }); }
  public markEmailSent(id: string) { return this.database.notification.update({ where: { id }, data: { emailStatus: EmailDeliveryStatus.SENT, emailSentAt: new Date(), emailError: null } }); }
  public markEmailFailed(id: string, error: string) { return this.database.notification.update({ where: { id }, data: { emailStatus: EmailDeliveryStatus.FAILED, emailError: error.slice(0, 500) } }); }
  public async list(userId: string, query: NotificationQuery) { const where: Prisma.NotificationWhereInput = { userId, deletedAt: null, ...(query.status ? { status: query.status } : {}), ...(query.type ? { type: query.type } : {}) }; const [items, total] = await this.database.$transaction([this.database.notification.findMany({ where, orderBy: { createdAt: 'desc' }, skip: (query.page - 1) * query.pageSize, take: query.pageSize }), this.database.notification.count({ where })]); return { items, total }; }
  public findOwned(id: string, userId: string) { return this.database.notification.findFirst({ where: { id, userId, deletedAt: null } }); }
  public async updateStatus(id: string, status: NotificationStatus, actor: NotificationActor) { return this.database.$transaction(async transaction => { const current = await transaction.notification.findFirst({ where: { id, userId: actor.userId, deletedAt: null } }); if (!current) throw new Error('NOTIFICATION_NOT_FOUND'); const updated = await transaction.notification.update({ where: { id }, data: { status, readAt: status === NotificationStatus.READ ? current.readAt ?? new Date() : status === NotificationStatus.UNREAD ? null : current.readAt, archivedAt: status === NotificationStatus.ARCHIVED ? new Date() : null } }); await transaction.auditLog.create({ data: { actorId: actor.userId, action: `NOTIFICATION_${status}`, entityType: 'Notification', entityId: id, requestId: actor.requestId } }); return updated; }); }
  public async markAllRead(actor: NotificationActor) { return this.database.$transaction(async transaction => { const result = await transaction.notification.updateMany({ where: { userId: actor.userId, status: NotificationStatus.UNREAD, deletedAt: null }, data: { status: NotificationStatus.READ, readAt: new Date() } }); await transaction.auditLog.create({ data: { actorId: actor.userId, action: 'NOTIFICATIONS_MARKED_READ', entityType: 'Notification', requestId: actor.requestId, after: { count: result.count } } }); return result.count; }); }
  public unreadCount(userId: string) { return this.database.notification.count({ where: { userId, status: NotificationStatus.UNREAD, deletedAt: null } }); }
  public async softDelete(id: string, actor: NotificationActor): Promise<void> { await this.database.$transaction(async transaction => { const current = await transaction.notification.findFirst({ where: { id, userId: actor.userId, deletedAt: null } }); if (!current) throw new Error('NOTIFICATION_NOT_FOUND'); await transaction.notification.update({ where: { id }, data: { deletedAt: new Date(), status: NotificationStatus.ARCHIVED, archivedAt: new Date() } }); await transaction.auditLog.create({ data: { actorId: actor.userId, action: 'NOTIFICATION_DELETED', entityType: 'Notification', entityId: id, requestId: actor.requestId } }); }); }
}
